# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockhelper', '0002_delete_stockquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=10)),
                ('risk', models.CharField(max_length=15)),
                ('openTime', models.DateTimeField()),
                ('highPrice', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lowPrice', models.DecimalField(decimal_places=4, max_digits=12)),
                ('openPrice', models.DecimalField(decimal_places=4, max_digits=12)),
                ('period', models.CharField(max_length=40)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
