# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockhelper', '0003_stockquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquote',
            name='closePrice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
